---
name: "Install Yamls precommit checks"
on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pre_commit:
    name: "Pre commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Set python version"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python -m pip install pre-commit

      - name: "Run pre-commit"
        run: |
          python -m pre_commit run -a
